FROM node:14.15-alpine as node-angular-cli

ENV APP_PATH /usr/app 

#Linux setup
RUN apk update \
  && apk add --update alpine-sdk \
  && apk del alpine-sdk \
  && rm -rf /tmp/* /var/cache/apk/* *.tar.gz ~/.npm \
  && npm cache verify \
  && sed -i -e "s/bin\/ash/bin\/sh/" /etc/passwd
 
WORKDIR $APP_PATH

#Angular CLI
RUN npm install -g @angular/cli